### ISSUE TITLE
Review wireframed template

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/cmi-innotech-website#3]
https://childmindinstitute.github.io/cmi-innotech-website/

**Comment by binarybottle** [comment]
Discussed with Jon and Curt.  Suggestions:

 - The cool roygbiv brain image visualization would be great except that we don't do brain imaging specifically in our group, and would be difficult for us to distinguish ourselves from the rest of the Center for the Developing Brain and prior CMI research.

 - The matrix representation, while internally helpful, may be more compactly represented on the website with icons (icons of people lining each project heading/image, icons of projects lining each person's image).  A visitor would want to click on the matrix squares, but the intersection of people and projects may not be easily represented.

 - Curt recommended that we have compelling media up front and center to draw in people.
