### ISSUE TITLE
Where to put advisory committee

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/cmi-innotech-website#4]
On the [Team](https://childmindinstitute.github.io/cmi-innotech-website/team/) page in another section?

Change the [Team](https://childmindinstitute.github.io/cmi-innotech-website/team/) page to People and divide into sections?

On a separate Advisory Committee page?

Elsewhere?

**Comment by binarybottle** [comment]
If we do an infinite scroll-type site that links to dedicated pages, then advisory committee could be toward the bottom, and linked from the top under something like "About".  Perhaps better would be to change "Team" to "Who we are" and list the team, clinical collaborators, advisors, etc.
